/*
 * 300 筆美式發音的 KK 音標對照。
 * 來源依 CMU Pronouncing Dictionary 的美式發音轉寫，口語片語逐字組合。
 */

export const PHONETICS = {
  "menu": "/ˈmɛnju/",
  "order": "/ˈɔrdɚ/",
  "meal": "/ˈmil/",
  "snack": "/ˈsnæk/",
  "ingredient": "/ˌɪnˈɡridiənt/",
  "delicious": "/dɪˈlɪʃəs/",
  "spicy": "/ˈspaɪsi/",
  "sweet": "/ˈswit/",
  "fresh": "/ˈfrɛʃ/",
  "vegetarian": "/ˌvɛdʒəˈtɛˌriən/",
  "dessert": "/dɪˈzɝt/",
  "beverage": "/ˈbɛvɚɪdʒ/",
  "appetite": "/ˈæpəˌtaɪt/",
  "portion": "/ˈpɔrʃən/",
  "refill": "/ˈriˌfɪl/",
  "bill": "/ˈbɪl/",
  "recommend": "/ˌrɛkəˈmɛnd/",
  "reserve": "/rɪˈzɝv/",
  "takeout": "/ˈteˌkaʊt/",
  "allergy": "/ˈælɚdʒi/",
  "grab a bite": "/ˈɡræb ə ˈbaɪt/",
  "eat out": "/ˈit ˈaʊt/",
  "on the house": "/ˈɑn ðə ˈhaʊs/",
  "to go": "/ˈtu ˈɡo/",
  "have a sweet tooth": "/ˈhæv ə ˈswit ˈtuθ/",
  "price": "/ˈpraɪs/",
  "cost": "/ˈkɑst/",
  "sale": "/ˈsel/",
  "discount": "/ˈdɪˌskaʊnt/",
  "cash": "/ˈkæʃ/",
  "receipt": "/rɪˈsit/",
  "customer": "/ˈkʌstəmɚ/",
  "cashier": "/kæˈʃɪr/",
  "budget": "/ˈbʌdʒɪt/",
  "brand": "/ˈbrænd/",
  "quality": "/ˈkwɑləti/",
  "size": "/ˈsaɪz/",
  "fit": "/ˈfɪt/",
  "exchange": "/ɪksˈtʃendʒ/",
  "refund": "/ˈriˌfʌnd/",
  "warranty": "/ˈwɔrənti/",
  "afford": "/əˈfɔrd/",
  "compare": "/kəmˈpɛr/",
  "purchase": "/ˈpɝtʃəs/",
  "coupon": "/ˈkuˌpɔn/",
  "bargain": "/ˈbɑrɡən/",
  "rip-off": "/ˈrɪp-ˈɔf/",
  "shop around": "/ˈʃɑp ɚˈaʊnd/",
  "sold out": "/ˈsold ˈaʊt/",
  "worth it": "/ˈwɝθ ˈɪt/",
  "station": "/ˈsteʃən/",
  "ticket": "/ˈtɪkət/",
  "platform": "/ˈplætˌfɔrm/",
  "route": "/ˈrut/",
  "traffic": "/ˈtræfɪk/",
  "passenger": "/ˈpæsəndʒɚ/",
  "destination": "/ˌdɛstəˈneʃən/",
  "departure": "/dɪˈpɑrtʃɚ/",
  "arrival": "/ɚˈaɪvəl/",
  "luggage": "/ˈlʌɡədʒ/",
  "passport": "/ˈpæˌspɔrt/",
  "journey": "/ˈdʒɝni/",
  "local": "/ˈlokəl/",
  "transfer": "/trænsˈfɝ/",
  "delay": "/dɪˈle/",
  "cancel": "/ˈkænsəl/",
  "explore": "/ɪkˈsplɔr/",
  "map": "/ˈmæp/",
  "direction": "/dɚˈɛkʃən/",
  "accommodation": "/əˌkɑməˈdeʃən/",
  "get around": "/ˈɡɛt ɚˈaʊnd/",
  "hit the road": "/ˈhɪt ðə ˈrod/",
  "red-eye flight": "/ˈrɛˌdaɪ ˈflaɪt/",
  "off the beaten path": "/ˈɔf ðə ˈbitən ˈpæθ/",
  "miss the bus": "/ˈmɪs ðə ˈbʌs/",
  "subject": "/ˈsʌbdʒɪkt/",
  "lesson": "/ˈlɛsən/",
  "homework": "/ˈhomˌwɝk/",
  "exam": "/ɪɡˈzæm/",
  "grade": "/ˈɡred/",
  "project": "/ˈprɑdʒɛkt/",
  "report": "/riˈpɔrt/",
  "research": "/ˈriˌsɝtʃ/",
  "knowledge": "/ˈnɑlədʒ/",
  "skill": "/ˈskɪl/",
  "focus": "/ˈfokəs/",
  "review": "/ˌrivˈju/",
  "practice": "/ˈpræktəs/",
  "memorize": "/ˈmɛmɚˌaɪz/",
  "understand": "/ˌʌndɚˈstænd/",
  "explain": "/ɪkˈsplen/",
  "submit": "/səbˈmɪt/",
  "deadline": "/ˈdɛdˌlaɪn/",
  "classmate": "/ˈklæˌsmet/",
  "scholarship": "/ˈskɑlɚˌʃɪp/",
  "cram for": "/ˈkræm ˈfɔr/",
  "catch up": "/ˈkætʃ ˈʌp/",
  "hand in": "/ˈhænd ɪn/",
  "figure out": "/ˈfɪɡjɚ ˈaʊt/",
  "learn by heart": "/ˈlɝn ˈbaɪ ˈhɑrt/",
  "account": "/əˈkaʊnt/",
  "profile": "/ˈproˌfaɪl/",
  "post": "/ˈpost/",
  "comment": "/ˈkɑmɛnt/",
  "message": "/ˈmɛsədʒ/",
  "follower": "/ˈfɑloɚ/",
  "content": "/ˈkɑntɛnt/",
  "upload": "/ˌʌˈplod/",
  "download": "/ˈdaʊnˌlod/",
  "privacy": "/ˈpraɪvəsi/",
  "password": "/ˈpæˌswɝd/",
  "online": "/ˈɔnˌlaɪn/",
  "digital": "/ˈdɪdʒətəl/",
  "search": "/ˈsɝtʃ/",
  "share": "/ˈʃɛr/",
  "block": "/ˈblɑk/",
  "flag": "/ˈflæɡ/",
  "notification": "/ˌnotəfəˈkeʃən/",
  "algorithm": "/ˈælɡɚˌɪðəm/",
  "influence": "/ˈɪnfluəns/",
  "go viral": "/ˈɡo ˈvaɪrəl/",
  "scroll through": "/ˈskrol ˈθru/",
  "DM someone": "/diɛm ˈsʌmˌwʌn/",
  "log in": "/ˈlɔɡ ɪn/",
  "unfollow": "/ənˈfɑlo/",
  "happy": "/ˈhæpi/",
  "sad": "/ˈsæd/",
  "angry": "/ˈæŋɡri/",
  "nervous": "/ˈnɝvəs/",
  "excited": "/ɪkˈsaɪtəd/",
  "worried": "/ˈwɝid/",
  "calm": "/ˈkɑm/",
  "proud": "/ˈpraʊd/",
  "lonely": "/ˈlonli/",
  "relaxed": "/rɪˈlækst/",
  "patient": "/ˈpeʃənt/",
  "honest": "/ˈɑnəst/",
  "generous": "/ˈdʒɛnɚəs/",
  "curious": "/ˈkjʊriəs/",
  "confident": "/ˈkɑnfədənt/",
  "shy": "/ˈʃaɪ/",
  "polite": "/pəˈlaɪt/",
  "responsible": "/riˈspɑnsəbəl/",
  "stubborn": "/ˈstʌbɚn/",
  "grateful": "/ˈɡretfəl/",
  "cheer up": "/ˈtʃɪr ˈʌp/",
  "freak out": "/ˈfrik ˈaʊt/",
  "feel down": "/ˈfil ˈdaʊn/",
  "open-minded": "/ˈopən-ˈmaɪndəd/",
  "easygoing": "/ˈiziˈɡoɪŋ/",
  "health": "/ˈhɛlθ/",
  "body": "/ˈbɑdi/",
  "exercise": "/ˈɛksɚˌsaɪz/",
  "sleep": "/ˈslip/",
  "pain": "/ˈpen/",
  "fever": "/ˈfivɚ/",
  "cough": "/ˈkɑf/",
  "headache": "/ˈhɛˌdek/",
  "medicine": "/ˈmɛdəsən/",
  "doctor": "/ˈdɑktɚ/",
  "hospital": "/ˈhɑˌspɪtəl/",
  "symptom": "/ˈsɪmptəm/",
  "energy": "/ˈɛnɚdʒi/",
  "habit": "/ˈhæbət/",
  "stress": "/ˈstrɛs/",
  "recover": "/rɪˈkʌvɚ/",
  "injury": "/ˈɪndʒɚi/",
  "treatment": "/ˈtritmənt/",
  "balanced": "/ˈbælənst/",
  "mental": "/ˈmɛntəl/",
  "work out": "/ˈwɝk ˈaʊt/",
  "under the weather": "/ˈʌndɚ ðə ˈwɛðɚ/",
  "get back on your feet": "/ˈɡɛt ˈbæk ˈɑn ˈjɔr ˈfit/",
  "cut down on": "/ˈkʌt ˈdaʊn ˈɑn/",
  "out of shape": "/ˈaʊt ˈʌv ˈʃep/",
  "home": "/ˈhom/",
  "room": "/ˈrum/",
  "kitchen": "/ˈkɪtʃən/",
  "bathroom": "/ˈbæˌθrum/",
  "bedroom": "/ˈbɛˌdrum/",
  "furniture": "/ˈfɝnɪtʃɚ/",
  "laundry": "/ˈlɔndri/",
  "chore": "/ˈtʃɔr/",
  "tidy": "/ˈtaɪdi/",
  "messy": "/ˈmɛsi/",
  "clean": "/ˈklin/",
  "repair": "/rɪˈpɛr/",
  "replace": "/ˌriˈples/",
  "electricity": "/ɪˌlɛkˈtrɪsəti/",
  "water": "/ˈwɔtɚ/",
  "neighbor": "/ˈnebɚ/",
  "rent": "/ˈrɛnt/",
  "balcony": "/ˈbælkəni/",
  "entrance": "/ˈɛntrəns/",
  "comfortable": "/ˈkʌmfɚtəbəl/",
  "sleep in": "/ˈslip ɪn/",
  "clean up": "/ˈklin ˈʌp/",
  "run out of": "/ˈrʌn ˈaʊt ˈʌv/",
  "feel at home": "/ˈfil ˈæt ˈhom/",
  "around the corner": "/ɚˈaʊnd ðə ˈkɔrnɚ/",
  "friend": "/ˈfrɛnd/",
  "family": "/ˈfæməli/",
  "relationship": "/riˈleʃənˌʃɪp/",
  "conversation": "/ˌkɑnvɚˈseʃən/",
  "invite": "/ˌɪnˈvaɪt/",
  "introduce": "/ˌɪntrəˈdus/",
  "promise": "/ˈprɑməs/",
  "trust": "/ˈtrʌst/",
  "respect": "/rɪˈspɛkt/",
  "support": "/səˈpɔrt/",
  "apologize": "/əˈpɑləˌdʒaɪz/",
  "forgive": "/fɚˈɡɪv/",
  "argue": "/ˈɑrɡju/",
  "agree": "/əˈɡri/",
  "advice": "/ædˈvaɪs/",
  "compliment": "/ˈkɑmpləmɛnt/",
  "guest": "/ˈɡɛst/",
  "community": "/kəmˈjunəti/",
  "contact": "/ˈkɑnˌtækt/",
  "cooperate": "/koˈɑpɚˌet/",
  "hang out": "/ˈhæŋ ˈaʊt/",
  "get along": "/ˈɡɛt əˈlɔŋ/",
  "keep in touch": "/ˈkip ɪn ˈtʌtʃ/",
  "make up": "/ˈmek ˈʌp/",
  "have your back": "/ˈhæv ˈjɔr ˈbæk/",
  "movie": "/ˈmuvi/",
  "music": "/ˈmjuzɪk/",
  "game": "/ˈɡem/",
  "sport": "/ˈspɔrt/",
  "hobby": "/ˈhɑbi/",
  "concert": "/ˈkɑnsɚt/",
  "episode": "/ˈɛpəˌsod/",
  "series": "/ˈsɪriz/",
  "character": "/ˈkɛrɪktɚ/",
  "performance": "/pɚˈfɔrməns/",
  "audience": "/ˈɑdiəns/",
  "creative": "/kriˈetɪv/",
  "relax": "/rɪˈlæks/",
  "enjoy": "/ˌɛnˈdʒɔɪ/",
  "collect": "/kəˈlɛkt/",
  "draw": "/ˈdrɔ/",
  "camp": "/ˈkæmp/",
  "photograph": "/ˈfotəˌɡræf/",
  "instrument": "/ˈɪnstrəmənt/",
  "entertainment": "/ˌɛntɚˈtenmənt/",
  "binge-watch": "/ˈbɪndʒ-ˈwɑtʃ/",
  "catch a movie": "/ˈkætʃ ə ˈmuvi/",
  "take up": "/ˈtek ˈʌp/",
  "kill time": "/ˈkɪl ˈtaɪm/",
  "page-turner": "/ˈpedʒ-ˈtɝnɚ/",
  "weather": "/ˈwɛðɚ/",
  "sunny": "/ˈsʌni/",
  "cloudy": "/ˈklaʊdi/",
  "rainy": "/ˈreni/",
  "windy": "/ˈwɪndi/",
  "storm": "/ˈstɔrm/",
  "temperature": "/ˈtɛmprətʃɚ/",
  "forecast": "/ˈfɔrˌkæst/",
  "climate": "/ˈklaɪmət/",
  "environment": "/ɪnˈvaɪrənmənt/",
  "nature": "/ˈnetʃɚ/",
  "pollution": "/pəˈluʃən/",
  "recycle": "/riˈsaɪkəl/",
  "reuse": "/riˈjuz/",
  "waste": "/ˈwest/",
  "renewable energy": "/riˈnuəbəl ˈɛnɚdʒi/",
  "earthquake": "/ˈɝθˌkwek/",
  "flood": "/ˈflʌd/",
  "drought": "/ˈdraʊt/",
  "sustainable": "/səˈstenəbəl/",
  "pouring": "/ˈpɔrɪŋ/",
  "clear up": "/ˈklɪr ˈʌp/",
  "cool down": "/ˈkul ˈdaʊn/",
  "eco-friendly": "/ˈiko-ˈfrɛndli/",
  "carbon footprint": "/ˈkɑrbən ˈfʊtˌprɪnt/",
  "job": "/ˈdʒɑb/",
  "work": "/ˈwɝk/",
  "career": "/kɚˈɪr/",
  "future": "/ˈfjutʃɚ/",
  "company": "/ˈkʌmpəˌni/",
  "office": "/ˈɔfɪs/",
  "manager": "/ˈmænədʒɚ/",
  "team": "/ˈtim/",
  "interview": "/ˈɪntɚvˌju/",
  "experience": "/ɪkˈspɪriəns/",
  "ability": "/əˈbɪləˌti/",
  "goal": "/ˈɡol/",
  "opportunity": "/ˌɑpɚˈtunəti/",
  "challenge": "/ˈtʃæləndʒ/",
  "success": "/səkˈsɛs/",
  "prepare": "/priˈpɛr/",
  "apply": "/əˈplaɪ/",
  "develop": "/dɪˈvɛləp/",
  "professional": "/prəˈfɛʃənəl/",
  "technology": "/tɛkˈnɑlədʒi/",
  "side hustle": "/ˈsaɪd ˈhʌsəl/",
  "move up": "/ˈmuv ˈʌp/",
  "start from scratch": "/ˈstɑrt ˈfrʌm ˈskrætʃ/",
  "think outside the box": "/ˈθɪŋk ˈaʊtˈsaɪd ðə ˈbɑks/",
  "in the long run": "/ɪn ðə ˈlɔŋ ˈrʌn/",
};

export default PHONETICS;
